name: Mix Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Elixir ${{ matrix.elixir }} with OTP ${{ matrix.otp }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        elixir:
          - '1.14'
          - '1.13'
          - '1.12'
          - '1.11'
        otp:
          - '25.1'
          - '25.0'
          - '24.3'
          - '23.3'
          - '22.3'
        exclude:
          - elixir: '1.14'
            otp: '23.3'
          - elixir: '1.14'
            otp: '22.3'
          - elixir: '1.12'
            otp: '25.1'
          - elixir: '1.12'
            otp: '25.0'
          - elixir: '1.11'
            otp: '25.1'
          - elixir: '1.11'
            otp: '25.0'

    services:
      redis:
        image: redis
        ports: ['6379:6379']

    steps:

      - name: Set up Elixir and OTP
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Restore cache for deps/ and _build/ directories'
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Install Mix dependencies
        run: mix deps.get

      - name: Run the tests
        run: mix test
